### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AlexZeitler** [shaunburdick/redact-object#7]
Thanks for building and releasing this package, that's exactly what I've been looking for.

Would you mind adding a `LICENSE` file so people know the permissions and restrictions about the usage of this library?

**Comment by shaunburdick** [comment]
Glad it worked for you! I added a [LICENSE file](https://github.com/shaunburdick/redact-object/commit/e434584adfde1e7f658a1d67bcdd612b419e5a4c) and updated some devDependencies to clear security audit. Pushed new version.

**Comment by AlexZeitler** [comment]
Thanks!
