### ISSUE TITLE
TypeScript errors when running tsc in depending project

### ISSUE THREAD

**Issue by AlexZeitler** [shaunburdick/redact-object#8]
I'm using `redact-object` in a TypeScript project. When running `tsc` for this project, I get this `tsc` error:

```shell
node_modules/redact-object/index.d.ts:23:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

23 function redact(
   ~~~~~~~~

node_modules/redact-object/index.d.ts:30:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

30 export = redact;
   ~~~~~~~~~~~~~~~~
```

**Comment by shaunburdick** [comment]
I rewrote the library in TS to autogen the typings. Let me know if that works for you!

**Comment by AlexZeitler** [comment]
@shaunburdick Great to hear. I just tried it and the error is resolved. Also all our tests are green so it seems to work - thanks 👍
